### ISSUE TITLE
Can't search brand "Origin-8"

### ISSUE THREAD

**Issue by lufte** [marketplacer/api.marketplacer.com#18]
I'm working with the bikexchange API.
The brands API doesn't return anything when searching for the brand "Origin-8". It seems that the inclusion of the hypen is what's causing the problem as it works when searching simply for "Origin".

`curl https://www.bikeexchange.coands/search?name=origin-8`

**Comment by mipearson** [comment]
This search functionality backs directly on to our ElasticSearch indices. This means that only words are indexed, not numbers, so (as you say) searching for "origin-8" will not work.

If you're trying to create adverts via our API with the correct taxon/brands, you might want to look at our new mapping functionality, which allows API integrations to submit taxons/brands as they appear on their customer systems and then map them via a customer interface: http://api.marketplacer.com/v2/adverts/#create-an-advert

**Comment by lufte** [comment]
Got it. Thanks.
