### ISSUE TITLE
Get invoice not return "Message to seller"

### ISSUE THREAD

**Issue by chewlim** [marketplacer/api.marketplacer.com#31]
I can't seem to find the message to seller field in the GET /api/v2/client/invoices/ call. 

Please advise

**Comment by robotdana** [comment]
You're right. it doesn't get returned.

I'll add it to our issue tracker and I'll update this card when it is done

**Comment by robotdana** [comment]
`message_to_seller: [string]` is included as an attribute of the `/api/v2/client/invoices` and `/api/v2/client/invoices/[id]` response
