### ISSUE TITLE
Adding an image

### ISSUE THREAD

**Issue by hagenschwass** [marketplacer/api.marketplacer.com#7]
Can you pls confirm that adding an image is working properly? I had serveral requests that had been working with v1 but are not working under v2:
* As stream content with content type header image/jpeg. Under v2 this does something like closing the connection (I get an AggregateException in C#)
* As multipart content. Under v2 it returns valid json code with
 * errors.detail="the data parameter is required"

**Comment by radar** [comment]
Hi @hagenschwass, do you have a `curl` example of the parameters that you're sending through?

**Comment by radar** [comment]
I think our documentation is a bit... lacking in this respect, and so I will update it to include a curl example soon.

**Comment by radar** [comment]
There's now a `curl` example there: 

![image](https://cloud.githubusercontent.com/assets/2687/10324749/c7d4cbf8-6cd7-11e5-968c-b231fb09c0d3.png)

What I reckon is happening is that you're submitting the parameter as `image`, rather than `data[attributes][image]`.

**Comment by radar** [comment]
We've discussed this internally and we'll be changing this endpoint to use just "image" as the parameter; so no more nesting in `data[attributes]`. We came to this conclusion because the `image` parameter is not a JSON blob for a typical JSON API action, and therefore shouldn't be treated like one. This should mean that your code should work as is after this change has been applied. 

I will comment here once more when that happens.

**Comment by radar** [comment]
This change has now been deployed to production. Please try again, @hagenschwass

**Comment by hagenschwass** [comment]
It is working as multipart content. Simple under "Content-Type: image/jpeg" there still happens something like connection closed (I have no better information), but actually I don't mind and use multipart. Havn't you wanted to support adding several images in one multipart content in v1?

**Comment by nhakhtn** [comment]
I tried this, but it not work
$service_url = 'https://www.bikeexchange.com/api/v2/client/adverts/100065329/images';
$curl = curl_init($service_url); 
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true); 
$data = array('data' => array('attributes' => array( 'image' => '@abc.png')));
$curl_post_data = json_encode($data);
curl_setopt($curl, CURLOPT_POSTFIELDS, $curl_post_data); 
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false); 
curl_setopt($curl, CURLOPT_HTTPHEADER, array('Authorization: Bearer d9cea...', 'Content-Type: application/vnd.api+json'));
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'POST'); 

 $curl_response = curl_exec($curl); 
 echo '<pre>'; $json = json_decode($curl_response); 
 echo json_encode($json, JSON_PRETTY_PRINT); echo '</pre>'; 
 curl_close($curl);

Please advice!
Thanks in advanced.
Regards!

**Comment by mipearson** [comment]
Hi,

We've changed the API due to the above confusion. Unfortunately, we forgot to push the corresponding update to the documentation.

Change:
`$data = array('data' => array('attributes' => array( 'image' => '@abc.png')));`

to:
`$data = array('image' => '@abc.png');`

**Comment by mipearson** [comment]
`'Content-Type: application/vnd.api+json'` is not required if what you are uploading is an image

**Comment by nhakhtn** [comment]
1. when i remove Content-Type: application/vnd.api+json, i got the message: "title": "Unsupported media type", "detail": "All requests must use the 'application\/vnd.api+json' Content-Type. This request specified 'application\/x-www-form-urlencoded'.",
2. when i add it again. then submit, i got the null response.
My code:
$service_url = 'https://www.bikeexchange.com/api/v2/client/adverts/100065329/images';
$curl = curl_init($service_url); 
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true); 
$data = array('image' => '@abc.png');
$curl_post_data = json_encode($data);
curl_setopt($curl, CURLOPT_POSTFIELDS, $curl_post_data); 
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false); 
curl_setopt($curl, CURLOPT_HTTPHEADER, array('Authorization: Bearer d9cea3f8810c19886d356d6ed87560ac', 'Content-Type: application/vnd.api+json'));
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'POST'); 

 $curl_response = curl_exec($curl); 

Btw, where i should put the abc.png file? i let it in same folder of my code (test.php)

Regards!

**Comment by hagenschwass** [comment]
I have to specify multipart content. "image/jpeg" does not work soley.

**Comment by mipearson** [comment]
@nhakhtn I can't help you with that, I'm afraid - you'll need to look up how to attach files using PHP's curl integration. The `@abc.jpg` format is valid for the command line, I suspect that doing so from within PHP is different.

You should not need to manually specify the content type for image uploads.

**Comment by nhakhtn** [comment]
it work well here via command line :), thanks so much! i am trying php ;)
